ui: mocha-bdd
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: 27..latest
  - name: ie
    version: 9..latest
  - name: iphone
    version: 6.1..latest
  - name: android
    version: 4.0..latest
